id: P0AD54B23
initial_creation_type: ocr
source_metadata:
  volumes:
    f08924ae3902432bb6ee12bb4207462d:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
